---

- name: Ensure that a logstash user is exist
  user: name={{logstash_user}} system=yes groups=adm

- name: Ensure that a logstash home is exist
  file: state=directory path={{logstash_home}} owner={{logstash_user}}

- include: install.deb.yml
  when: ansible_os_family == 'Debian'
  tags: [logstash, logstash-install]

- include: configure-common.yml
  tags: [logstash, logstash-configure]

- include: configure-server.yml
  when: logstash_server_enabled
  tags: [logstash, logstash-configure]

- include: configure-forwarder.yml
  when: logstash_forwarder_enabled
  tags: [logstash, logstash-configure]

- name: use wazuh default config file
  template:
    src=01-ossec-singlehost.conf
    dest={{logstash_confdir}}/conf.d/01-ossec-singlehost.conf
  when: logstash_config_wazuh_default
  notify: [logstash restart]
